..FF..FFF.
Failed tests:
-------------
1) TestAnotherThing.test3_Fail1
test/test_with_err_fail_pass.lua:50: expected: 0, actual: 2
stack traceback:
	test/test_with_err_fail_pass.lua:50: in function 'TestAnotherThing.test3_Fail1'

2) TestAnotherThing.test3_Fail2
test/test_with_err_fail_pass.lua:54: expected: 0, actual: 3
stack traceback:
	test/test_with_err_fail_pass.lua:54: in function 'TestAnotherThing.test3_Fail2'

3) TestSomething.test2_Fail1
test/test_with_err_fail_pass.lua:16: expected: 0, actual: 2
stack traceback:
	test/test_with_err_fail_pass.lua:16: in function 'TestSomething.test2_Fail1'

4) TestSomething.test2_Fail2
test/test_with_err_fail_pass.lua:20: expected: 0, actual: 3
stack traceback:
	test/test_with_err_fail_pass.lua:20: in function 'TestSomething.test2_Fail2'

5) testFuncFail1
test/test_with_err_fail_pass.lua:63: expected: 0, actual: 3
stack traceback:
	test/test_with_err_fail_pass.lua:63: in function 'testFuncFail1'

Ran 10 tests in 0.001 seconds, 5 successes, 5 failures, 5 non-selected
